### ISSUE TITLE
Fatal error during installation

### ISSUE THREAD

**Issue by StephaneBullier** [the-fast-track/book-5.0-3#1]
When I use command `symfony new --version=5.0-3 --book guestbook` after step "Stopping the SymfonyCloud tunnel:" I have this error message "fatal: 'step-29' n'est pas un commit et une branche 'work-step-29' ne peut pas en être créée depuis" and "exit status 128"

**Comment by fabpot** [comment]
I forgot to push the tags for this new version of the code. This has been fixed now.
