### ISSUE TITLE
Problem with functional test after add second comment to fixtures

### ISSUE THREAD

**Issue by StephaneBullier** [the-fast-track/book-5.0-3#2]
To pass the tests I need to update two thinks in  `$this->assertSelectorExists()` sentences.
First : `$this->assertSelectorExists('div:contains("There are 1 comments.")');` become `$this->assertSelectorExists('div:contains("There are 2 comments.")');`

Second: `$this->assertSelectorExists('div:contains("There are 2 comments.")');` become `$this->assertSelectorExists('div:contains("There are 3 comments.")');` after simulate comment validation

It's right or not ?

**Comment by fabpot** [comment]
It really depends on what you've done and what you in DB. So, the book gives a possible example but your count number can indeed be different.
