### ISSUE TITLE
Diff between help message of messenger:consume 

### ISSUE THREAD

**Issue by StephaneBullier** [the-fast-track/book-5.0-3#3]
The help message for messenger:consume `php bin/console messenger:consume <receiver-name> --time-limit=3600` use = between --time-limit and value
In the .symfony.cloud.yaml, you use this option without =
php bin/console messenger:consume async -vv --time-limit 3600 --memory-limit=128M

Perhaps a typo error ?

**Comment by fabpot** [comment]
Both works fine.
